---
title: "Acknowledgment"
order: 4
---

When reporting results, creating a publication, working on any other public disclosure involving ABCD Study® data, please use the ABCD word marks or logo marks shown below and refer to [this guidance](https://abcdstudy.org/wp-content/uploads/2020/04/ABCD_Trademarks_Service_Marks-1.pdf) for appropriate use.

Be sure to use the appropriate acknowledgment language to reference the ABCD Study® as the source of the original data. This language is documented in the Acknowledgments section of the Terms and Conditions of the Data Use Certification, and is reproduced below.


>Data used in the preparation of this article were obtained from the **[Adolescent Brain Cognitive Development™ (ABCD) Study](https://abcdstudy.org/)**, held in the **[NIH Brain Development Cohorts Data Sharing Platform](https://www.nbdc-datahub.org/)**. This is a multisite, longitudinal study designed to recruit more than 10,000 children aged 9–10 and follow them over 10 years into early adulthood.

>The ABCD Study® is supported by the **National Institutes of Health** and additional federal partners under award numbers:

>`U01DA041048`, `U01DA050989`, `U01DA051016`, `U01DA041022`, `U01DA051018`, `U01DA051037`, `U01DA050987`, `U01DA041174`, `U01DA041106`, `U01DA041117`, `U01DA041028`, `U01DA041134`, `U01DA050988`, `U01DA051039`, `U01DA041156`, `U01DA041025`, `U01DA041120`, `U01DA051038`, `U01DA041148`, `U01DA041093`, `U01DA041089`, `U24DA041123`, `U24DA041147`.

>A full list of supporters is available at [Federal Partners – ABCD Study](https://abcdstudy.org/federal-partners.html).

>ABCD Consortium investigators designed and implemented the study and/or provided data but did not necessarily participate in the analysis or writing of this report. This manuscript reflects the views of the authors and may not reflect the opinions or views of the NIH or ABCD Consortium investigators.


**Add the following sentence for a report that uses data from a versioned release:** 

>The ABCD data repository grows and changes over time. The ABCD data used in this report came from [NIMH Data Archive Digital Object Identifier (DOI)]. DOIs can be found at [DOI URL].

**Add the following sentence for a report that uses linked external environmental data:**

>Additional support for this work was made possible from NIEHS R01-ES032295 and R01-ES031074.

**Add the following sentence for a report that uses data from the ABCD-SD substudy:**

>This project was supported by Award Number 2017-MU-CX-0044, awarded by the National Institute of Justice, Office of Justice Programs, U.S. Department of Justice with additional funding from the Centers for Disease Control and Prevention, U.S. Department of Health and Human Services. The opinions, findings, and conclusions or recommendations expressed in this publication/program/exhibition are those of the author(s) and do not necessarily reflect those of the Department of Justice or the Department of Health and Human Services.

:::{.callout-note title="Current 5.1 data users"}
Users who are using data from the ABCD 5.1 release, should refer to the acknowledgement page on NDA: <https://nda.nih.gov/abcd/abcd-citing>.
:::
