---
title: "Changelog"
order: 3
---


# 7.0.0
<span style="font-size: 0.85em; color: gray;">
**Date:** 2026-05-18<br>
**URL:** [https://docs.abcdstudy.org/v/7_0_0](https://docs.abcdstudy.org/v/7_0_0)
</span>

-   **General**
    -   Updated new design layout for the website
    -   Updated 7.0 domain tables
    -   Updated 7.0 overview and sample
    -   Added new datasets and summary scores

-   **Non-Imaging**
    -   Updated relevant content, see the 7.0 release notes

-   **Imaging**
    -   Updated relevant content, see the 7.0 release notes
    
-   **ABCC**
    -   Updated ABCC with the changes pertaining to 7.0 data release

-   **Tools**
    -   Added documentation regarding R/Python Packages for NBDCtools
    
-   **Substudies**
    -   Added documentation for Baby Teeth, RECOVER, and Structured Interview for Psychosis Risk Syndromes (SIPS) 
    
-   **FAQ**
    -   Added question/answer regarding slice timing correction in the processing of minimally processed fMRI data



# 6.1.3
<span style="font-size: 0.85em; color: gray;">
**Date:** 2026-04-09<br>
**URL:** [https://docs.abcdstudy.org/v/6_1_3](https://docs.abcdstudy.org/v/6_1_3)
</span>

-   **Non-Imaging**
    -   Mental Health: Updated Youth Self Report content regarding removed items
    -   Neurocognition: Updated Flanker and NIH Toolbox content regarding remote administration
    -   Novel Technologies: Updated EARS pilot content regarding the year of administration
    -   Substance Use: Updated TLFB content regarding time period in interview
    -   Substance Use: Updated Toxicology content regarding the protocols
    -   Substance Use: Updated Parental Rule for ENDS Use content regarding missing data

-   **Imaging**
    -   Updated content regarding ABCD3 atlas 
    -   Updated ABCC content

-   **Release Notes**
    -   Add 6.0 Mental Health release notes regarding Youth Self Report missing scales

-   **Access and Download Data**
    -   Removed requirement regarding holding an active FWA



# 6.1.2
<span style="font-size: 0.85em; color: gray;">
**Date:** 2026-02-12<br>
**URL:** [https://docs.abcdstudy.org/v/6_1_2](https://docs.abcdstudy.org/v/6_1_2)
</span>

-   **Release Notes**
    -   Added Imaging 6.0 release notes regarding scanner issue for site 15
    -   Added Physical Health 6.0 release notes regarding `ph_p_sds` missing `dtt` variable
    -   Added Mental Health 6.1 release notes regarding `mh_y_ksads__suic`
    -   Added Mental Health 6.0 release notes regarding `mh_p_ksads_bpd` and `mh_y_ksads_bpd`
    -   Added Social Development 6.0 release notes regarding integer fields with non-response data and age fields with outlier data




# 6.1.1
<span style="font-size: 0.85em; color: gray;">
**Date:** 2026-01-08<br>
**URL:** [https://docs.abcdstudy.org/v/6_1_1](https://docs.abcdstudy.org/v/6_1_1)
</span>

-   **Non-imaging**
    -   Mental Health: Updated KSADS tables with the correct administration of modules at each year
    -   Mental Health: Updated Life Events content with the item changes for events
-   **Imaging**
    -   Added in prior changes to the Imaging Methods
-   **Release Notes**
    -   Added Linked External Data 6.0 release notes regarding `le_l_o3`
    -   Updated Genetics 6.1 release notes regarding genetics relatedness matrix
    -   Added Physical Health 6.0 release notes regarding `ph_y_pq` variable naming error
    -   Added Mental Health 6.0 release notes regarding Life events summary scores, Life events item coding error, BIS/BAS summary score error, and EATQ summary score error
    -   Added Imaging 6.0 release notes regarding indicator variables, missing values in tabulated imaging data, and mismatched rows in concatenated data




# 6.1.0
<span style="font-size: 0.85em; color: gray;">
**Date:** 2025-12-03<br>
**URL:** [https://docs.abcdstudy.org/v/6_1_0](https://docs.abcdstudy.org/v/6_1_0)
</span>

-   **General Changes**
    -   Updated 6.1 pdfs for download below the domain tables
-   **Release Notes**
    -   Added the 6.1 Release Notes pertaining to the 6.1 data release
-   **FAQ**
    -   Added question/answer regarding the recommendations for cell size in the FAQ section
-   **ABCC**
    -   Updated ABCC with the changes pertaining to 6.1 data release




# 6.0.3
<span style="font-size: 0.85em; color: gray;">
**Date:** 2025-10-16<br>
**URL:** [https://docs.abcdstudy.org/v/6_0_3](https://docs.abcdstudy.org/v/6_0_3)
</span>

-   **General Changes**
    -   All domain overview tables are now available to download as a pdf
-   **Tools**
    -   CMIG Pipeline documentation has been added
-   **Curation & Structure**
    -   Updated the curation standard's session/event identifier table to now include mapping to prior release naming where applicable
-   **Release Notes**
    -   A downloadable curation brochure pdf is available for users
    -   Added release note regarding `ab_g_dyn__cohort_income__hhold` summary scores levels
    -   Added release note regarding time point mapping errors in the Domain Overview tables
    -   Added release note regarding known issues in Neurocognition (`nc_y_lmt` and `nc_y_nihtb`)
    -   Added release note with regard to `ph_y_bp` summary scores
    -   Added release note with regard to error in `mh_y_bpm` and `mh_t_bpm` tables
    -   Added release note with regard to `mh_p_asr` table




# 6.0.2
<span style="font-size: 0.85em; color: gray;">
**Date:** 2025-09-18<br>
**URL:** [https://docs.abcdstudy.org/v/6_0_2](https://docs.abcdstudy.org/v/6_0_2)
</span>

-   **General Changes**

    -   Reorganized content to better align with table order and domain

-   **Non-imaging**

    -   **Novel Technologies:** Updated content regarding EARS data

-   **Release Notes**

    -   Updated Mental Health Release Notes regarding KSADS - Suicidality Youth items




# 6.0.1
<span style="font-size: 0.85em; color: gray;">
**Date:** 2025-08-19<br>
**URL:** [https://docs.abcdstudy.org/v/6_0_1](https://docs.abcdstudy.org/v/6_0_1)
</span>

-   **General Changes**
    -   Added callout boxes to data documentation that direct users to the relevant Release Notes section
-   **Non-imaging**
    -   **Linked External Data:** Fixed and updated some citations
-   **Imaging**
    -   **Source data / raw data:** Added a known issue regarding mismatch between the tabulated and BIDS (sourcedata and rawdata) in the anonymized MRI scanner serial numbers
    -   **MRI derivatives:** Added example code to run pipeline with ABCD sourcedata
-   **Release Notes**
    -   Updated Mental Health Release Notes regarding KSADS
-   **Tools**
    -   Added content regarding utility functions as part of the NBDCtools R package




# 6.0.0
<span style="font-size: 0.85em; color: gray;">
**Date:** 2025-07-03<br>
**URL:** [https://docs.abcdstudy.org/v/6_0_0](https://docs.abcdstudy.org/v/6_0_0)
</span>

Initial version of the data documentation website for ABCD release 6.0.0
