---
title: "ABCD-BIDS community collection"
order: 1
---

## <i class="fa-solid fa-brain"></i>&nbsp; About ABCC

The **ABCD-BIDS Community Collection (ABCC)** is a curated MRI dataset derived from the ABCD Study. It uses the [Brain Imaging Data Structure (BIDS)]((https://bids-specification.readthedocs.io/)) and [NMIND](https://www.nmind.org/about) reproducibility framework to provide **standardized, ready-to-use raw and derivative data** for rapid and reproducible scientific discovery.

All data included in ABCC have passed **[DAIRC](https://abcdstudy.org/study-sites/daic/) quality control**. Data are processed using **peer-reviewed, open-source pipelines developed within the [NMIND](https://www.nmind.org/about) framework**, ensuring consistent and reproducible neuroimaging outputs (see [Processing & Analytic Standards](abcc_pipeline.qmd#processing-analytic-standards)). Derivative quality control is performed using [BrainSwipes](https://brainswipes.us/), a community-driven visual QC platform (*learn more and contribute [here](abcc_qualitycontrol.qmd#brainswipes)*).

::: {.callout-note title="See @feczko2021 for details."}
:::

### <i class="fa-solid fa-caret-right"></i> Key Features

<ul class="fa-ul">
<li><span class="fa-li"><i class="fa-regular fa-star"></i></span> <strong>BIDS-Standardized</strong>: Follows <a href="https://bids-specification.readthedocs.io/">BIDS</a> standard for reproducible, cross-study analyses.</li>
<li><span class="fa-li"><i class="fa-regular fa-star"></i></span> <strong>NMIND-Reviewed Pipelines</strong>: Peer-reviewed processing pipelines via <a href="https://www.nmind.org/about">NMIND</a>.</li>
<li><span class="fa-li"><i class="fa-regular fa-star"></i></span> <strong>Surface + Volume Outputs</strong>: Includes CIFTI, NIfTI, and GIFTI derivatives.</li>
<li><span class="fa-li"><i class="fa-regular fa-star"></i></span> <strong>Quality Control</strong>: Visual QC of both raw (<a href="https://abcdstudy.org/study-sites/daic/">DAIRC</a> QC) and processed (<a href="https://brainswipes.us/">BrainSwipes</a>) data.</li>
<li><span class="fa-li"><i class="fa-regular fa-star"></i></span> <strong>Versioned Releases</strong>: Each release includes detailed version tracking and change logs.</li>
<li><span class="fa-li"><i class="fa-regular fa-star"></i></span> <strong>Continuously Updated</strong>: Updated alongside new ABCD data releases.</li>
</ul>   

### <i class="fa-solid fa-caret-right"></i> High-Impact Studies

**ABCC data has powered a variety of impactful neuroscience research, with more than 90 published studies referencing the collection.** A full list of publications and formatted citation files are available [here](https://drive.google.com/...).

::: {.callout-note collapse="false" title="Highlights"}
- **@marek2019**: Identifying reproducible individual differences in childhood functional brain networks: An ABCD study (*Developmental Cognitive Neuroscience*)
- **@chaarani2021**: Task activation patterns in 9-10 year old youths 
- **@cieslak2021**: QSIPrep: an integrative platform for preprocessing and reconstructing diffusion MRI data (*Nature Methods*)
- **@bethlehem2022**: Brain Charts for the human lifespan
- **@marek2022**: Reproducible brain behavior associations require thousands of samples
- **@gordon2023**: Identification of the human SCAN network, revolutionizing our understanding of the human motor system.
- **@keller2023**: Functional topography is associated with youth cognition
- **@hermosillo2024**: Individualized functional network mapping in adolescents (*Nature Neuroscience*)
- **@keller2024**: Environmental exposures mediate the association between functional topography and cognition
- **@mehta2024**: XCP-D: an extensible pipeline for rs-fMRI connectivity preprocessing
:::

## <i class="fa-regular fa-note-sticky"></i>&nbsp; Release Notes (v3.1.0) {#release-notes-v310}

::: {.callout-note title="Release Date: 2025-06-26"}
:::

### <i class="fa-solid fa-caret-right"></i> Core Data

ABCC includes **BIDS input data** converted from raw DICOM format and **derivatives** generated from multiple processing pipelines. See the [Data processing](abcc_pipeline.qmd) page for pipeline processing details and [Derivatives](abcc_derivatives.qmd) page for a detailed list of derivatives included in this release for each of the following pipelines.

| Pipeline    | Description |
| ---------------- | ----------- |
| [ABCD-HCP BIDS v0.1.4](https://abcd-hcp-pipeline.readthedocs.io/) | HCP-style MRI processing pipeline in volume & surface space | 
| FreeSurfer 5.3.0-HCP | Segmentation statistics & surface morphometrics | 
| [QSIPrep](https://qsiprep.readthedocs.io/) | Pre-processed diffusion-weighted MRI | 
| [QSIRecon](https://qsirecon.readthedocs.io/) | Reconstruction of pre-processed dMRI data | 
| [QSIRecon-ModelArray](https://pennlinc.github.io/ModelArray/) | Mean Diffusivity .h5 and .csv files for voxel-wise modeling | 

### <i class="fa-solid fa-caret-right"></i> Data Availability

*Number of participants with ABCD-HCP and QSIPrep derivatives by study year. Values in brackets indicate raw BIDS counts.*

| Year     | ABCD-HCP: *Derivatives [raw BIDS]* | QSIPrep: *Derivatives [raw BIDS]* |
|:---------|:----------------------------------|:--------------------------------|
| Baseline | 11,751 [11,753]                  | 8,852 [9,564]                  |
| 2        | 8,086 [8,085]                    | 7,273 [7,669]                  |
| 4        | 6,351 [6,355]                    | 6,066 [6,207]                  |
| 6        | 3,820 [3,820]                    | 3,676 [3,748]                  |

### <i class="fa-solid fa-caret-right"></i> New Data

- **QSIRecon** reconstruction derivatives generated from preprocessed diffusion MRI data using the following reconstruction specifications:
    - **Diffusion tensor modeling**: DSI Studio (all b-values), TORTOISE (b < 1200), DIPY (as part of DKI)
    - **Diffusion kurtosis modeling**: DIPY
    - **Q-space imaging**: DSI Studio 
    - **NODDI models**: AMICO
    - **Tractography**: DSI Studio AutoTrack on MSMT FODs (from MRtrix3)

- **QSIRecon-ModelArray** - A single HDF5 (.h5) file and corresponding CSV file containing Mean Diffusivity (MD) values from all subjects in the current QSIRecon output. These files enable efficient voxelwise model fitting in R using the **[ModelArray package](https://github.com/PennLINC/ModelArray)**, allowing users to compute and write model-fitted parameters, p-values, and R² maps back into NIfTI files.

### <i class="fa-solid fa-caret-right"></i> Key Revisions

Resolved critical issues in abcd-hcp-pipeline derivatives:

- **Missing Volume-Based Resting-State Data (Runs 3–8)**: Restored missing data by re-executing the file-mapper across all participants
- **Missing nBack Filtered Concatenated dtseries**: Generated missing files using the using [abcc_concat_filtered_dtseries_generator tool](https://github.com/DCAN-Labs/abcc_concat_filtered_dtseries_generator) for all participants.
- **Timepoint Mismatch Resolution**: Resolved timepoint mismatches between filtered dtseries ( `*_task-*_bold_desc-filtered_timeseries.dtseries.nii`)and motion mask files ( `*_task-*_desc-filtered_motion_mask.mat`)( N ~ 746 ) [(View affected cases)](https://abcd-docs-private.lassoinformatics.com/release_notes/imaging/6.0_imaging_abcc.html)
- **Duplicate Functional Runs**: Reprocessed 861 cases through complete BIDS conversion and abcd-hcp-pipeline re-execution [(View affected cases)](https://abcd-docs-private.lassoinformatics.com/release_notes/imaging/6.0_imaging_abcc.html)

::: {.callout-important title="NOTE: QSIPrep Distortion Correction Fix"}
**Users of earlier QSIPrep derivatives are encouraged to reprocess analyses to account for the distortion correction fix.** In the prior release. TOPUP being given a denoised b=0 image from the DWI series and a raw b=0 image in the opposite phase encoding direction, resulted in inaccurate distortion correction results for a subset of subjects. The updated version uses unprocessed b=0 images in both phase encoding directions.
:::

### <i class="fa-solid fa-caret-right"></i> Known Issues

::: {.callout-warning title="Missing Cases from Duplicate Run Reprocessing"}
During reprocessing of duplicate functional runs, four cases failed due to out-of-memory errors and are not included in the current release. Derivatives for these cases remain available in previous releases and can be accessed if needed. [(View affected cases)](https://abcd-docs-private.lassoinformatics.com/release_notes/imaging/6.0_imaging_abcc.html)
:::

## <i class="fa-solid fa-hourglass-half"></i>&nbsp; Coming Soon

- **Structural & functional MRI** processed through **[fMRIPrep](https://fmriprep.org)** and **[XCP-D](https://xcp-d.readthedocs.io)**
- **Task fMRI pipeline results**
- **Individualized network maps** [@hermosillo2024]

## <i class="fa-solid fa-clock-rotate-left"></i>&nbsp; Release History

::: {.callout-important title="Release 3.0 changes"}
The below release history reflects releases previously available through the [NIMH Data Archive (NDA)](https://nda.nih.gov/). Starting with Release 3.0.0 (2025-06-26), the ABCC is made available through the [NBDC Data Hub](https://www.nbdc-datahub.org/) and does not reflect revisions made to the NDA repository. The release history for versions 2.0.0 and below are provided below for legacy purposes. Please visit the [ABCC Archival Data Release Documentation](https://nda-abcd-collection-3165.readthedocs.io) for the archived release documentation associated wih the data available for prior releases via the NDA.  
:::

::: {.callout-note collapse="true" title="Release 3.0.0 (2025-06-26)"}
**REVISIONS**

1. **Updated abcd-hcp-pipeline v0.1.4:**: Enhanced BIDS compliance, streamlined directory structure, updated ExecutiveSummary QC, and improved BOLD bandpass filtering. (see changes [here](https://github.com/DCAN-Labs/abcd-hcp-pipeline/releases/tag/v0.1.4)) 
1. **Fixed incorrect AP/PA labeling** in subset of GE dv26 subjects.
1. **Updated QSIPrep v0.21.4** (see changes [here](https://github.com/PennLINC/qsiprep/releases/tag/0.21.4)): Critical fixes to distortion correction and QC metric calculation.

**Important Note**: Users of earlier QSIPrep derivatives are encouraged to reprocess analyses to account for the distortion correction fix. In the prior release, TOPUP was given a denoised b=0 image from the DWI series and a raw b=0 image in the opposite phase encoding direction, resulting in inaccurate distortion correction for a subset of subjects. The updated version uses unprocessed b=0 images in both phase encoding directions.

**NEW ADDITIONS**

1. Additional inputs and derivatives for **Years 2, 4, and 6**
1. Expanded **QSIPrep** diffusion derivatives
1. New `sessions.tsv` files with session demographics, acquisition timestamps, scanner metadata, and automated QC metrics. Structural QA columns include BOLD brain coverage Pass/Fail indicators (`bc_(task)_run-(run_num)`) based on 10% threshold, coverage percentages (`bc_(task)_run-(run_num)_perc_vox`), and outlier counts for subcortical segmentation volumes (n=22) and cortical morphometry (n=333). Functional QA columns include Pass/Fail indicators for 5- and 10-minute connectivity matrix generation (`5min_pconn_<atlas>`, `10min_pconn_<atlas>`) and corresponding outlier counts (n=61776) across five parcellation schemes: Gordon2014, HCP2016, Markov2012, Power2011, and Yeo2011 (all with FreeSurferSubcortical). Values of 888 indicate missing or ungenerated files, except for pconn Pass/Fail columns.

**KNOWN ISSUES**

1. **Missing Volume-Based Resting-State Run Files (Runs 3–8):** Due to a transfer issue, some minimally processed, volume-based resting-state data are missing for runs 3–8 (mainly affecting data from Years 4 and 6). **Surface-based CIFTI data — used by most researchers — are fully available and unaffected.** Affected files include:

    - `*_task-rest_run-{3-8}_motion.tsv`
    - `*_task-rest_run-{3-8}_space-MNI_bold.nii.gz`
    - `*_task-rest_run-{3-8}_desc-filteredincludingFD_motion.tsv`

    These files were restored in v3.1.0 patch release. Users who required these files could also regenerate them from the concatenated motion files using the [abcd-abcc_motion_reg_generator](https://github.com/nbdc-datahub/abcd-abcc_motion_reg_generator) utility (see its documentation for details).
:::

::: {.callout-note collapse="true" title="Release 2.0.0 (2022-06-22)"}
**REVISIONS**

1. **Uploading 144 participants with new data due to revised fast track QC**: The initial release was processed prior to new updates to the fast track QC spreadsheet that affected the original inputs for 144 participants. This led to discrepancies in the number of timepoints reported for connectivity matrices (see below) relative to the inputs. The 144 participants were re-processed through the ABCD-BIDS pipeline at the Minnesota Supercomputing Institute (MSI). The `participants.tsv` file indicates which subjects were reprocessed. These subjects have new Gordon 10 and 5 minute connectivity matrices generated and replaced on the NDA. The old matrices remain valid, but may use different frames from the new matrices. The labels for the updated connectivity matrices were defined in @gordon2016 and generated using the [DCAN Labs cifti connectivity wrapper](https://github.com/DCAN-Labs/cifti-connectivity/) at a frame displacement (FD) threshold of 0.2 mm to filter out high-motion frames. An outlier detection procedure was used to exclude remaining frames 2 STD from the mean.
1. **Providing Connectivity matrices** for those participants with discrepancies in the number of timepoints used
1. **Uploading JSONs for the diffusion inputs** in some participants.
1. **Updated version of the participants.tsv to v1.0.2** includes correction to site and sex designation for a small subset of subjects based on new information from the DAIRC.

**NEW ADDITIONS**

1. **Individualized Network Maps Generated with Infomap and Template Matching (*Submission ID: 36448*)**
1. **Derivatives for the fmriprep pipeline:** fMRIPrep v20.2.0 was run on all 10,038 participants whose visit one data was successfully converted to BIDS. The limited fMRIPrep processing errors were due to subjects that did not have any valid fMRI runs, but we did not do any manual quality control of outputs. 9,484 participants have at least one output. The data is available in 18 submissions (a summary, including number of files and submission size can be found [here](https://docs.google.com/spreadsheets/d/1NbZ28vBvGVJb9miivgsJ695VVoFBSBuBQmWigN5pg_c/edit#gid=678992105)). Detailed information about the files included in each submission are on the second tab of that spreadsheet. Files with no submission name listed have not yet been uploaded.
1. **DWI sidecar JSON patch (Diffusion inputs) (*Submission IDs: 36449 - 36452*)**: The DWI acquisition parameters from subjects scanned on Philips and GE with MR Software release versions 5.3.0_5.3.0.0 and DV25.0_R02_1549.b respectively (n=423) are missing the required field, PhaseEncodingDirection. This omission is because they reported the axis and not direction; therefore we did a manual check of these images to check the phase encoding direction, so that these JSON inputs are BIDS compatible and can be processed by pipelines like QSIprep. These JSONs have been updated and uploaded.
1. **Level-2 task files from the ABCD-task-fMRI pipeline (*Submission IDs: 36458 - 36630*)**
:::

::: {.callout-note collapse="true" title="Release 2.0.0 (2022-06-22)"}
**REVISIONS**

1. **Uploading 144 participants with new data due to revised fast track QC**: The initial release was processed prior to new updates to the fast track QC spreadsheet that affected the original inputs for 144 participants. This led to discrepancies in the number of timepoints reported for connectivity matrices (see below) relative to the inputs. The 144 participants were re-processed through the ABCD-BIDS pipeline at the Minnesota Supercomputing Institute (MSI). The `participants.tsv` file indicates which subjects were reprocessed. These subjects have new Gordon 10 and 5 minute connectivity matrices generated and replaced on the NDA. The old matrices remain valid, but may use different frames from the new matrices. The labels for the updated connectivity matrices were defined in @gordon2016 and generated using the [DCAN Labs cifti connectivity wrapper](https://github.com/DCAN-Labs/cifti-connectivity/) at a frame displacement (FD) threshold of 0.2 mm to filter out high-motion frames. An outlier detection procedure was used to exclude remaining frames 2 STD from the mean.
1. **Providing Connectivity matrices** for those participants with discrepancies in the number of timepoints used
1. **Uploading JSONs for the diffusion inputs** in some participants.
1. **Updated version of the participants.tsv to v1.0.2** includes correction to site and sex designation for a small subset of subjects based on new information from the DAIC.

**NEW ADDITIONS**

1. **Individualized Network Maps Generated with Infomap and Template Matching (*Submission ID: 36448*)**
1. **Derivatives for the fmriprep pipeline:** fMRIPrep v20.2.0 was run on all 10,038 participants whose visit one data was successfully converted to BIDS. The limited fMRIPrep processing errors were due to subjects that did not have any valid fMRI runs, but we did not do any manual quality control of outputs. 9,484 participants have at least one output. The data is available in 18 submissions (a summary, including number of files and submission size can be found [here](https://docs.google.com/spreadsheets/d/1NbZ28vBvGVJb9miivgsJ695VVoFBSBuBQmWigN5pg_c/edit#gid=678992105)). Detailed information about the files included in each submission are on the second tab of that spreadsheet. Files with no submission name listed have not yet been uploaded.
1. **DWI sidecar JSON patch (Diffusion inputs) (*Submission IDs: 36449 - 36452*)**: The DWI acquisition parameters from subjects scanned on Philips and GE with MR Software release versions 5.3.0_5.3.0.0 and DV25.0_R02_1549.b respectively (n=423) are missing the required field, PhaseEncodingDirection. This omission is because they reported the axis and not direction; therefore we did a manual check of these images to check the phase encoding direction, so that these JSON inputs are BIDS compatible and can be processed by pipelines like QSIprep. These JSONs have been updated and uploaded.
1. **Level-2 task files from the ABCD-task-fMRI pipeline (*Submission IDs: 36458 - 36630*)**
:::

::: {.callout-note collapse="true" title="Release 1.1.1 (2020-10-07)"}
This was a small version 1.0.0 release of the `derivatives_qc.(json|tsv)` with additional BIDS derivatives quality control data including a "brain coverage score" for the `derivatives.func.runs_task-(MID|nback|rest|SST)_volume` data subsets.
:::

::: {.callout-note collapse="true" title="Release 1.1.0 (2020-07-27)"}
**NEW ADDITIONS**

- 157 additional subjects due to updated fast track QC spreadsheet
- `participants.(json|tsv)` version 1.0.0: BIDS standard participants files with matched groups
- `sourcedata.func.task_events`: Task-based fMRI E-Prime files
- `inputs.dwi.dwi`: DWI BIDS input data
- `derivatives.anat.stats`: FreeSurfer stats files
- `derivatives.anat.(T1w|T2w)`: T1 and T2 volumes
- `derivatives.anat.wmparc`: white-matter volume ROIs
- `derivatives.func.updated_motion_task-(MID|nback|SST|rest)`: Improved motion files (including outlier calculation)
- `derivatives.func.pconns`: Curated parcellated connectivity files
- `derivatives.func.runs_task-(MID|nback|SST|rest)_volume`: Minimally-processed fMRI volumes
:::

::: {.callout-note collapse="true" title="Release 1.0.0 (2020-02-17)"}
This was the initial release of DCAN Labs ABCD-BIDS inputs and derivatives containing **10,038 MRI sessions worth of NDA imagingcollection01 data** and **9,647 MRI sessions worth of NDA fmriresults01 data**.

**KNOWN ISSUES**

- `sourcedata`: Event Related Information `sourcedata` files can be csv files as well as txt files, but this release only includes the txt files
- `task-rest_bold.json`: Discovered in the middle of June 2020, the modality-specific BIDS inherited `task-rest_bold.json` file at the top of the directory tree which is nested in almost every `task-rest` associated record in the NDA database has a typo in it. The `"TaskDescription"` key has a value of `"See http://www.cognitiveatlas.org/task/id/tsk_4a57abb949e1a/"`. However, this link goes to the stop signal task page on the Cognitive Atlas website. Instead you should refer to [the Cognitive Atlas website for "rest eyes open"](http://www.cognitiveatlas.org/task/id/trm_4c8a834779883/). This website describes the task as: "Subjects rest passively with their eyes open. Often used as a baseline for comparison for other tasks."
- `derivatives.func.runs_task-rest_volume`: This data subset was originally uploaded in Release 1.1.0, but was missing all runs chronologically numbered 3 and up. We are uploading these missing data in Release 1.1.2.
- `updated_dwi_input_json`: The DWI acquisition parameters from all subjects scanned on GE with MR Software release DV25.0_R02_1549.b (n=281) are missing the required field, PhaseEncodingDirection. This omission is because they reported the axis and not direction.
:::
