---
title: "Trial level behavioral performance during task-based fMRI"
---

```{r}
#| label: setup
#| include: false 

for (file in list.files("../../../R", full.names = TRUE)) source(file)
```

# Domain overview

To facilitate use of trial-level behavioral performance data from the different task-based fMRI a set of pre-processing steps that can be applied to the stimulus event timing and behavioral performance files was developed for ABCD.The code used to implement these pre-processing steps has been made publicly available on the ABCD Study’s [GitHub page](https://github.com/ABCD-STUDY). The input E-prime files are available in the sourcedata BIDS structure (see MRI Raw Data File Sharing Data Documentation). The E-prime task files used for ABCD are available at <https://abcdstudy.org/scientists/abcd-fmri-tasks-and-tools>. The tasks and the summary behavioral performance measures extracted from the E-prime files and included in the tabulated data are described in the Behavioral Performance Data Documentation. The processing and analysis of the associated fMRI data is described in Task-Based fMRI Data Documentation. The behavioral performance review is part of the ABCD Study QC procedures and recommended imaging inclusion criteria (see MRI Quality Control Data Documentation).

::: {#use-trial .callout-important title="Responsible Use Warning: Trial-Level Data" collapse="true"}

Using open-access datasets like ABCD requires responsible conceptualization and use of the data, including being mindful of variations in experience that impact performance. Below are specific considerations:

- Cognitive task performance can be influenced by various environmental and personal factors, including participant health, attention, nutrition, fatigue, or other transient conditions.Cognitive task performance has been shown to correlate strongly with a variety of socio-economic factors. Attention and other performance factors can also be confounded by transient factors influenced by low SES, such as fatigue, poor nutrition, or environmental stressors.
- Although the ABCD protocol captures several environmental and personal variables that may influence performance (e.g., potential covariates), it is unlikely that all relevant factors have been measured.Although the ABCD protocol captures several SES-related variables (e.g. for use as potential covariates), it is unlikely that the ABCD dataset captures all of them.
:::

# Trial-Level Behavioral Data

## Monetary Incentive Delay (MID) Task

The following table provides the column names that are contained within the MID pre-processed behavioral data files, as well as a brief description of the variable and what type of data it contains.

|  |  |
|------------------------------------|------------------------------------|
| **Column name** | **Description** |
| `task` | Behavioral task completed |
| `subject` | Subject ID ashow it’s defined in lab/project |
| `eventname` | The event name for which the data was collected |
| `site` | Data collection site ID |
| `date` | Date of data collection (month/day/year) |
| `time` | Time that data was collected (hours/minutes/seconds) |
| `mid_run` | Which run the task data corresponds to `mid_trialnum` |
| `mid_anticipationtype` | The type of anticipation for that trial |
| `mid_anticipationonset` | The time that the anticipation phase started |
| `mid_anticipationduration` | The length of time that the anticipation phase lasted |
| `mid_feedbacktype` | The type of feedback received based on the subject’s performance `mid_feedbackonset` |
| `mid_feedbackduration` | The length of time that the feedback phase lasted |
| `mid_acc` | Accuracy of the subject’s performance for that trial |
| `mid_resp` | Whether or not the subject provided a response for that `trialmid_rt` |
| `mid_rttime` | The timepoint in the task when the participant responded |
| `mid_trialmoney` | The money resulting from the subject’s performance on that trial |

The following information pertains to the variables:

- `mid_anticipationonset`
- `mid_anticipationduration`
- `mid_feedbackonset`
- `mid_feedbackduration`
- `mid_rt`
- `mid_rttime`

1.  All times have already been corrected and represent the actual start time of the task.

- In other words, as this task was carried out as an fMRI task, the “PrepTime” times for each of the runs has already been subtracted out, producing the times contained in the pre-processed behavioral data files. These times are consistent with those produced by the abcd_extract_eprime scripts, which are publicly-available in the ABCD study’s [GitHub page](https://github.com/ABCD-STUDY).
- If you are analyzing these behavioral data with the MID fMRI data and you do not plan on removing any initial frames prior to analysis, you must adjust the mid_anticipationonset, mid_feedbackonset, and mid_rttime variables in the following way:
  - Siemens/Philips Scanners: Add 6400 ms
  - GE DV25: Add 4000 ms
  - GE DV26: Add 12,800 ms

2.  All times are presented in milliseconds

## Stop Signal Task (SST)

The following table provides the column names that are contained within the SST pre-processed behavioral data files, as well as a brief description of the variable and what type of data it contains.

|  |  |
|------------------------------------|------------------------------------|
| **Column name** | **Description** |
| `task` | Behavioral task completed |
| `src_subject_id` | Subject IDeventname |
| `site` | Data collection site ID |
| `date` | Date at which the data were collected |
| `time` | Local time at which the data were collected |
| `sst_run` | Whether the trial occurred on the first or second run of the task |
| `sst_trialnum` | E-Prime-labeled trial number within each run (note: these numbers are generated by E-Prime and do not necessarily correspond with the absolute trial number; e.g., the first trial in a run may be labeled as number 3) |
| `sst_stimonset` | Variable constructed by the trial-level task force (see [Appendix B](#appendix-b)) that indicates the global onset time of each trial |
| `sst_beginfix_starttime` | Global “start time” (when an E-Prime slide is scheduled to be presented) for the fixation slide that began each run; this time should correspond to the beginning of fMRI data collection for the run |
| `sst_beginfix_onsettime` | Global “onset time” (when an E-Prime slide actually begins to be presented) for the fixation slide that began each run |
| `sst_stim` | Variable constructed by the trial-level task force (see [Appendix B](#appendix-b)) that indicates the choice stimulus presented for the trial (right- or left-facing arrow) |
| `sst_stimfile` | Name of the .bmp file for the presented choice stimulus, which was used to compute the “sst_stim” variable |
| `sst_primaryresp` | Variable constructed by the trial-level task force (see [Appendix B](#appendix-b)) that indicates the first response the participant made on each trial (right- or left-facing arrow) |
| `sst_primaryrt` | Variable constructed by the trial-level task force (see [Appendix B](#appendix-b)) that indicates the response time for the first response the participant made on each trial |
| `sst_go_onsettime` | Global onset time for “go” slidessst_go_resp |
| `sst_go_rt` | Response times locked to the beginning of “go” slides |
| `sst_go_rttime` | Global timing of responses to “go” slides |
| `sst_ssd_onsettime` | Global onset time for “ssd” `slidessst_ssd_resp` |
| `sst_ssd_rt` | Response times locked to the beginning of “ssd” slides |
| `sst_ssd_rttime` | Global timing of responses to “ssd” slides |
| `sst_ssd_dur` | Duration of the stop-signal delay (SSD) for STOP trials |
| `sst_stopsignal_onsettime` | Global onset time for “stopsignal” `slidessst_stopsignal_resp` |
| `sst_stopsignal_rt` | Response times locked to the beginning of “stopsignal” slides |
| `sst_stopsignal_rttime` | Global timing of responses to “stopsignal” slides |
| `sst_fix_onsettime` | Global onset time for “fix” `slidessst_fix_resp` |
| `sst_fix_rt` | Response times locked to the beginning of “fix” slides (note: the global timing of responses to “fix” slides was not recorded by the task) |
| `sst_leftarrow` | Variable that maps participants’ button press responses to the “left arrow” response |
| `sst_rightarrow` | Variable that maps participants’ button press responses to the “right arrow” response |
| `sst_expcon` | Whether the trial was in the GO or STOP condition |
| `sst_choiceacc` | Variable constructed by the trial-level task force (see [Appendix B](#appendix-b)) for whether participants’ response to the choice task (left- vs. right-facing arrow) was accurate (1) or inaccurate (0) |
| `sst_inhibitacc` | Variable constructed by the trial-level task force (see [Appendix B](#appendix-b)) indicating, for STOP trials, whether participants successfully inhibited (1) or failed to inhibit (0) |

### Concerns regarding ABCD SST task

@bissett2020 raised several concerns about the design and data recording procedures of the ABCD SST. Trial-level data users are encouraged to read this manuscript, as well as our response @garavan2020), and the outline (see [Appendix A](#appendix-a) below) of how each identified concern affects the trial-level data in this release. Two of the concerns raised have particularly important implications for the inclusion of individual subjects:

1. The fact that a subset of individuals display response time (RT) data that cannot be explained by the standard SST Independent Race Model (mean failed STOP RT \> mean GO RT)

2. A data recording glitch, which occurs when a participant makes a fast (\<50ms) response on a STOP trial with a 50ms stop-signal delay and which causes all subsequent STOP trials to be incorrectly recorded as failures to stop with the same RT, altering the tracking algorithm. Therefore, in addition to the standard ABCD performance exclusion criteria outlined above, users interested in applying race models of inhibition to the trial-level data are encouraged to exclude participants from analysis who have the following flags:
- Participants with mean STOP RT \> mean GO RT, indicating clear violations of Independent Race Model assumptions (`tfmri_sst_beh_violatorflag`)
- Participants who display evidence of the recording glitch, as outlined in [Appendix A](#appendix-a) (`tfmri_sst_beh_glitchflag`)

However, if users are primarily interested in analyzing features of performance on the GO choice task (e.g., GO RT variability), such exclusions may not be necessary.

Task trials involved the presentation of stimuli on several different slides in E-Prime: GO trials involved the presentation of a “go” slide with the choice stimulus for 1000ms, or until a participant responded, followed by a “fix” slide which presented a fixation cross for the remaining duration of the 1000ms trial and jittered intertrial interval; STOP trials involved the presentation of a “ssd” slide with the choice stimulus for the duration of the variable stop-signal delay on that trial, followed by a “stopsignal” slide that presented the stop signal (upward facing arrow) for 300ms, and finally by a “fix” slide which presented a fixation cross for the remaining duration of the 1000ms trial plus the duration of the jittered intertrial interval. The recording of RTs and responses was linked to the individual slide, rather than being locked to the onset of the trial.

To facilitate use of the trial-level data, the ABCD trial-level behavioral data (TLBD) task force applied minimal pre-processing steps (outlined in [Appendix B](#appendix-b)) to determine the first response a participant made on each trial (sst_primaryresp variable), which in standard research contexts is treated as the participant’s main response, and accurately estimates the RT for this response (`sst_primaryresp` variable). However, all relevant response, RT and onset timing variables from the individual slides have been retained, as described below, which will allow other researchers to compute response and RT variables using their own methods, if desired.

When possible, participants who were unable to complete the task in the scanner, completed the task behaviorally outside the scanner on a laptop computer. Whether a participant performed the SST in the scanner or on a laptop is indicated by the following variable in the main tabulated data: `mr_y_adm__nts__tfmri__sst_indicator`. For more details, see the [MRI Scanning Checklist and Notes](admin.qmd#mr_y_adm__nts) instrument.

### Appendix A {#appendix-a}

**Details on the specific issues raised in the “Cautionary Note” manuscript by Bisset et al, and how they affect the use of these trial-level data.**

As noted above, a manuscript entitled “A cautionary note on stop-signal data from the Adolescent Brain Cognitive Development \[ABCD\] study” (@bissett2020) raised several concerns about the ABCD SST’s design and data recording procedures. Users of the trial-level data are encouraged to read this manuscript and any associated commentaries prior to analyzing these data. For clarity, this section provides a brief summary of each concern and the specific implications that these concerns present for analysis of the trial-level data included in this release.

**1\. Different “go” choice stimulus presentation durations across trials.**

*Summary:*

On GO trials, the choice stimulus (a right- or left-facing arrow) is presented on screen until the participant responds or until a 1000ms window passes, whichever occurs first. However, on STOP trials, the visual stop signal (an upward facing arrow) replaces the “go” choice stimulus following the stop-signal delay. This causes the presentation time of the choice stimulus to be substantially shorter, on average, for STOP trials than for GO trials, which likely makes the choice task more difficult in the STOP condition. The increase in difficulty likely yields slower and less accurate choice responses in this condition (particularly for STOP trials with relative short stop-signal delays). The Independent Race Model, which is the dominant framework for estimating the main index of inhibition on the SST (stop-signal reaction time; SSRT) assumes context independence, which means that the “go” choice process and its average finishing time are not affected by the presentation of the stop signal (i.e., that the “go” process is identical between GO and STOP trials). As context independence is essential for accurate estimation of SSRT in the race model, and as the choice stimulus presentation durations of the ABCD SST likely cause violations of the context independence assumption, especially at short stop-signal delays, SSRT estimates drawn from applications of the race model to these data could be inaccurate.

*Implications for the use of trial-level data:*

This issue does not affect the accurate recording of trial-level data, but it does present a problem for applications of SSRT measurement models, such as at the Independent Race Model, that assume context independence. However, the extent to which this design feature impacts estimates of SSRT, and whether this impact has a substantial effect on the rank ordering of subjects (i.e., whether individuals with high vs. low inhibitory ability still show relatively high and low SSRT estimates, respectively, even if the absolute values of SSRT are biased), has yet to be determined. Future experimental or computational modeling studies could help provide greater clarity about these questions. Current users are encouraged to carefully consider the assumptions of any measurement model they apply to these data and to consider the possible limitations of parameter estimates and measures derived from any model that assumes context independence. Another important implication related to this assumption is that individual participants who display mean RT on failed STOP trials that is longer than mean RT on GO trials (which occurs in a small subset of ABCD participants) exhibit a pattern of data that cannot be explained by a race model that assumes context independence. Therefore, users interested in applying models with this assumption should consider excluding these participants (who can be identified with the tfmri_sst_beh_violatorflag variable) as violators of the independence assumption.

**2\. “Go” choice stimulus is not presented on STOP trials with a 0ms stop-signal delay.**

*Summary:*

This is a special case of the first issue discussed above. Since the visual stop-signal stimulus replaces the “go” choice stimulus after the stop-signal delay, the choice stimulus is not actually presented on trials where the stop-signal delay is 0ms. This may violate assumptions of measurement models applied to the task (including the Independent Race Model) and may confuse participants.

*Implications for the use of trial-level data:*

Similar to the first issue discussed above, the implications of this feature depend on the assumptions of the specific measurement model being applied to the data and whether users believe that this feature would substantially impact their ability to test their specific research question. Users may consider excluding these trials from analysis and/or excluding participants with a large proportion of these trials if they determine that doing so is appropriate. To facilitate these participant-level exclusions, variable tfmri_sst_beh_0ssdcount provides a count of how many 0ms stop-signal delay trials each participant has.

**3\. A glitch leads to incorrect stop-signal delays for some participants.**

*Summary:*

Due to a glitch in the experimental program, if a participant makes a response in \<50ms on a STOP trial where the stop-signal delay is equal to 50ms, all subsequent STOP trials will be erroneously recorded as having a response with the exact same RT on the “ssd” slide. Because these trials are incorrectly coded as stopping failures by the experimental program, all subsequent stop-signal delays will be stuck at 0ms. As the conditions that trigger this glitch are very specific, it is only present in about 3% of participants.

*Implications for the use of trial-level data:*

As this glitch leads incorrect values of `sst_ssd_rt` to be recorded on subsequent trials and leads to stop-signal delays that do not correspond to the task’s standard staircase pattern, users are encouraged to exclude participants who show evidence of the glitch (who can be identified with the `tfmri_sst_beh_glitchflag` variable). However, users should also note that, because the glitch primarily affects the `sst_ssd_rt` variable, but the pre-processing steps (outlined in Appendix B) ignore the “ssd” slide on trials with 0ms stop-signal delays, the constructed variables in the trial-level data (`sst_primaryresp`, `sst_primaryrt`, `sst_choiceacc`, `sst_inhibitacc`) should be accurate for subsequent trials.

**4\. Stop-signal duration is shorter for trials with stop-signal delays \>700ms.**

*Summary:*

If the stop-signal delay for a given STOP trial is \>700ms, the stop-signal stimulus is not presented for the standard 300ms and is instead presented for a shorter duration (1000ms minus the stop-signal delay). As the Independent Race Model assumes “stop” context independence in addition to “go” context independence, and the shorter presentation time on these trials may violate this assumption, these trials may be inappropriate to include in race model analyses.

*Implications for the use of trial-level data:*

As these trials are relatively rare (roughly 1% of STOP trials in the data set), users may consider excluding them from analysis and/or excluding participants with a large proportion of these trials if they determine that doing so is appropriate.

**5\. Non-uniform conditional trial probability.**

*Summary:*

As reviewed in detail in Bisset et al, the probability of encountering a stop signal on a given trial in the ABCD SST is not uniform and instead depends on the recency of previous STOP trials. The most notable feature of the conditional trial probability distribution is that STOP trials are never repeated two times in a row, which could allow participants to learn this contingency and therefore improve their performance on the task. However, the authors provide evidence that, at least for the baseline ABCD session, participants did not appear to learn the contingency.

*Implications for the use of trial-level data:*

Unless users encounter compelling evidence that participants are learning the conditional trial probability contingencies, no adjustments are necessary.

**6\. Trial accuracy incorrectly coded.**

*Summary:*

The experimental program incorrectly classified a small number (\<1%) of correct “go” choices as incorrect “go” choices and a small number (2-3%) of incorrect “go” choices as correct “go” choices. In addition, \<1% of stop failure trials were incorrectly classified as correctly inhibited STOP trials. These incorrect classifications were recorded in a column of the raw E-Prime output (“TrialCode”) that is not included in this trial-level data release and was not used to generate any of the constructed variables in the minimally pre-processed data columns.

*Implications for the use of trial-level data:*

As the column with these errors is not included in the data release, and as these errors would only have minimal impacts on participants’ stop-signal delays produced by the tracking algorithm, no adjustments are necessary.

**7\. Stop-signal delay values start at 50ms.**

*Summary:*

The initial stop-signal delay value of 50ms, which is relatively low, could present problems if it leads to abnormally high stop success rates on the first few trials of the task or if it drives participants to shift their strategy over the course of the experiment. The authors provide evidence that stopping accuracy is elevated on the first 10 trials relative to the rest of the trials, and specifically that the first 7 trials have stop success rates \> .60.

*Implications for the use of trial-level data:*

Users can consider removing the first 7 to 10 STOP trials of the task or conducting separate sensitivity analyses in which these trials are removed.

**8\. Low STOP trial probability.**

*Summary:*

The authors point out that the stop trial probability on the ABCD SST (.167) is somewhat lower than stop trial probabilities on most other SST paradigms (.25-.33). However, there are currently no indications that this low stop trial probability impacts inferences from the task.

*Implications for the use of trial-level data:*

Unless users encounter compelling evidence that this design feature impacts inferences, no adjustments are necessary.

### Appendix B {#appendix-b}

**Details of minimal pre-processing steps**

These pre-processing steps were conducted to facilitate the use of the trial-level data in most applications by creating variables that record participants’ first response on each trial (regardless of which slide this response occurs on), the global onset times of each trial, easily interpretable names for the stimuli and responses, and variables that indicate separately whether participants made accurate decisions on the choice task and whether they succeeded in inhibiting responses on STOP trials. The code used to implement the following pre-processing steps have been made publicly available on the ABCD-STUDY GitHub: <https://github.com/ABCD-STUDY>.

1\. Create general stimulus onset variable for all trials

- For GO trials –\> set `sst_stimonset` = `sst_go_onsettime`
- For STOP trials in which `sst_ssd_dur > 0ms` –\> set `sst_stimonset` = `sst_ssd_onsettime`
- For STOP trials in which `sst_ssd_dur` = 0ms –\> set `sst_stimonset` = `sst_stopsignal_onsettime`

2\. Create variable with details of the presented stimulus

- For any trial in which `sst_stimfile` = "images/Right_Arrow.bmp" –\> set `sst_stim = "right_arrow"`
- For any trial in which `sst_stimfile` = "images/Left_Arrow.bmp" –\> set `sst_stim = "left_arrow"`

3\. Determine response mapping for the participant

- Responses on the E-Prime slides (`sst_go_resp`, `sst_fix_resp`, `sst_ssd_resp`, `sst_stopsignal_resp`) are sometimes recorded as integers (e.g., 1 or 2) and sometimes recorded as strings (e.g., “LEFTARROW”). Therefore, the mapping between raw response data and the “right_arrow” and “left_arrow” responses must be established for each participant. If raw responses were integers, the `sst_leftarrow` and `sst_rightarrow` columns were used to establish response mapping. If raw responses were strings, the presence of “right” or “left” in the string was used to establish response mapping.

4\. Compute primary response and primary RT for GO trials

- If the participant’s first response on the trial is during the “go” slide, the RT and response from that slide (`sst_go_rt` and `sst_go_resp`) are recorded as the participant’s primary RT and response for that trial. Subsequent responses during the following “fix” slide are ignored.
- If the participant’s first response on the trial is instead during the “fix” slide (i.e., their response latency was \>1000ms), the reconstructed RT (`sst_fix_rt` + 1000) and the response (`sst_fix_resp`) from the “fix” slide are recorded as the participant’s primary RT and response for that trial.
- If the participant fails to respond during either the “go” or “fix” slide, their response and RT on that trial are treated as missing (blank)

5\. Compute primary response and primary RT for STOP trials

- If `sst_ssd_dur` \> 0ms AND `sst_ssd_dur` \> \<700ms:
  - If the participant’s first response on the trial is during the “ssd” slide, the RT and response from that slide (`sst_ssd_rt` and `sst_ssd_resp`) are recorded as the participant’s primary RT and response for that trial. Subsequent responses during the following “stopsignal” and “fix” slides are ignored.
  - If the participant’s first response on the trial is during the “stopsignal” slide, the reconstructed RT (`sst_stopsignal_rttime - sst_ssd_onsettime`) and the response (`sst_stopsignal_resp`) from that slide are recorded as the participant’s primary RT and response for that trial. Subsequent responses during the following “fix” slide are ignored.
  - If the participant’s first response on the trial is during the “fix” slide, the reconstructed RT (`sst_fix_rt + 300 + sst_ssd_dur`) and the response (`sst_fix_resp`) from that slide are recorded as the participant’s primary RT and response for that trial.
  - If the participant fails to respond during any of these three slides, their primary response and RT on that trial are treated as missing (blank)
- If `sst_ssd_dur` = 0ms:
  - If the participant’s first response on the trial is during the “stopsignal” slide, the RT (`sst_stopsignal_rt`) and the response (`sst_stopsignal_resp`) from that slide are recorded as the participant’s primary RT and response for that trial. Subsequent responses during the following “fix” slide are ignored.
  - If the participant’s first response on the trial is during the “fix” slide, the reconstructed RT (`sst_fix_rt` + 300) and the response (`sst_fix_resp`) from that slide are recorded as the participant’s primary RT and response for that trial.
  - If the participant fails to respond during either of the two slides, their response and RT on that trial are treated as missing (blank)
- If `sst_ssd_dur` \> 700ms:
  - Same procedures as used above (for if `sst_ssd_dur` is \>0ms and \<700ms) are implemented, unless the first response is on the “fix” slide, in which case the RT is calculated simply as `sst_fix_rt` + 1000

6\. Compute accuracy variables

- To compute the sst_choiceacc variable for each trial:
  - If `sst_primaryresp` = NA/blank –\> set `sst_choiceacc` = NA/blank
  - If `sst_primaryresp` ≠ NA/blank AND `sst_stim` = `sst_primaryresp` –\> set `sst_choiceacc` = 1
  - If `sst_primaryresp` ≠ NA/blank AND `sst_stim` ≠ `sst_primaryresp` –\> set `sst_choiceacc` = 0
- To compute the sst_inhibitacc variable for each trial:
  - If `sst_expcon` = GoTrial, `sst_inhibitacc` = NA/blank
  - If `sst_expcon` ≠ GoTrial AND `sst_primaryresp` = NA/blank –\> set `sst_inhibitacc` = 1
  - If `sst_expcon` ≠ GoTrial AND `sst_primaryresp` ≠ NA/blank –\> set `sst_inhibitacc` = 0

## Emotional nBack Working Memory Task

|  |  |
|------------------------------------|------------------------------------|
| **Column name** | **Description** |
| `task` | Behavioral task completed |
| `subject` | Subject IDeventname |
| `site` | Data collection site ID |
| `date` | Date at which the data were collected |
| `time` | Local time at which the data were collected |
| `enback_trialnum` | Variable constructed by the trial-level task force which indicates the trial number within each run |
| `enback_run` | Variable constructed by the trial-level task force which indicates the run number |
| `enback_runtrialnumber[Block]` | E-Prime-labeled trial number (note: these numbers are generated by E-Prime and do not necessarily correspond with the absolute trial number; e.g., the first trial may be labeled as number 3) |
| `enback_cue0back_onsettime` | Global onset time for the cues that begin 0-back blocks |
| `enback_cue2back_onsettime` | Global onset time for the cues that begin 2-back blocks |
| `enback_stim_onsettime` | Global onset time for each stimulus |
| `enback_fix_onsettime` | Global onset time for the intertrial interval following each stimulus, during which a fixation cross is presented |
| `enback_cuefix_starttime` | Global start time of the fixation cross presentation that precedes each block (note: the first of these times in each run should correspond to the beginning of fMRI data collection for that run) |
| `enback_loadcon` | N-back load condition (0-back or 2-back) |
| `enback_stimtype` | Emotion condition (PosFace, NegFace, NeutFace, Place) of the stimulus |
| `enback_targettype` | Target status (target, lure, nonlure) of the stimulus |
| `enback_stimfile` | Name of the specific .bmp image presented for each stimulus |
| `enback_stim_resp` | Participant’s button press response |
| `enback_stim_rt` | Response time |
| `enback_stim_acc` | Whether the participant’s choice was accurate |
| `enback_stim_rttime` | Global time of the response to the trial |

Although most of the variables in this release were drawn from the raw E-Prime output, two variables (enback_trialnum and enbackrun) were computed with minimal pre-processing steps carried out by the ABCD trial-level task force. The code used to implement these pre-processing steps has been made publicly available on the ABCD Study’s [GitHub page](https://github.com/ABCD-STUDY).

When possible, participants who were unable to complete the task in the scanner, completed the task behaviorally outside the scanner on a laptop computer. Whether a participant performed the nBack task in the scanner or on a laptop is indicated by the following variable in the main tabulated data: ra_scan_cl_nbac_scan_lap. For more details, see the [MRI Scanning Checklist and Notes](admin.qmd#mr_y_adm__nts).

Note on global timing variables: All global timing variables reflect the raw global times recorded in E-Prime, which are locked to the beginning of the E-Prime task. As fMRI data begin to be collected some time after the experimenter starts the E-Prime task, users interested in locking events in the trial-level data to the fMRI data will need to transform these global times by subtracting the global start time of each run from all global timing variables (as detailed in the variable descriptions above).

